name: Multi-platform Build with PyInstaller

on:
  push:
    branches:
      - 1.x.x

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.12.7']
      fail-fast: false  # 禁止失败快速终止
      max-parallel: 1   # 每次只运行一个平台
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tomlkit aiofiles aiohttp

      - name: Install UPX
        shell: bash
        run: |
          UPX_VERSION="5.0.1"
          case "$RUNNER_OS" in
            Windows)
              curl -L -o upx.zip "https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-win64.zip"
              unzip upx.zip
              mkdir -p upx-win
              mv upx-${UPX_VERSION}-win64/* upx-win/
              echo "$(pwd)/upx-win" >> $GITHUB_PATH
              ;;
            Linux)
              curl -L -o upx.tar.xz "https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.xz"
              tar -xf upx.tar.xz
              echo "$(pwd)/upx-${UPX_VERSION}-amd64_linux" >> $GITHUB_PATH
              ;;
            macOS)
              brew install xz
              curl -L -o upx-src.tar.xz "https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-src.tar.xz"
              tar -xJf upx-src.tar.xz
              cd upx-${UPX_VERSION}
              # 编译 UPX
              make -f Makefile.osx
              # 将编译后的 upx 添加到 PATH
              echo "$(pwd)/src" >> $GITHUB_PATH
              ;;
          esac

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcfilefetcher-${{ runner.os }}-binaries
          path: dist/