name: Build EXE with PyInstaller

on:
  push:
    branches:
      - 1.x.x  # 或你想要触发的分支

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tomlkit aiofiles aiohttp
          
      - name: Install UPX
        run: |
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip" -OutFile "upx.zip"
          Expand-Archive -Path "upx.zip" -DestinationPath "C:\tools\upx"
          echo "C:\tools\upx" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --upx-dir "C:\tools\upx" McFileFetcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: McFileFetcher1.1.0
          path: dist/McFileFetcher.exe

